version: '3.9'

services:
  energo_db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: energo_db
      POSTGRES_USER: energo_user
      POSTGRES_PASSWORD: energo_pass
    command: ["postgres", "-p", "7002"]
    volumes:
      - energo_postgres_data:/var/lib/postgresql/data
    ports:
      - "7002:7002"

  backend:
    build: ./backend
    env_file:
      - ./backend/.env.example
    environment:
      DB_ENGINE: postgres
      POSTGRES_DB: energo_db
      POSTGRES_USER: energo_user
      POSTGRES_PASSWORD: energo_pass
      POSTGRES_HOST: energo_db
      POSTGRES_PORT: 7002
    volumes:
      - ./backend:/app
    ports:
      - "7001:7001"
    depends_on:
      - energo_db

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:7001/api/
    ports:
      - "7000:80"
    depends_on:
      - backend

volumes:
  energo_postgres_data:
